### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gillchristian** [getlistas/api#12]
Frontend TODOs: https://github.com/gillchristian/doneq/issues/3

## MVP

- [ ] Handle public resource authentication
- [ ] Create fork endpoint (Public Lists)
- [ ] `GET /users` endpoint
- [ ] Lists to have slug for nicer URLs in the client. Eg. `/lists/:user_slug/:list_slug`
- [x] Add image to resource model
- [x] Create endpoint to parse title from URL
- [x] Update `/list/list_id/resources` response to be sorted and filtered by not `completed_at`
- [x] IDs should be strings instead of `{ "$oid": "5fde5f20008acb7700c1bf36" }`
- [x] Dates should be strings instead of `{ "$date": "2020-12-27T22:41:53.596Z" }`

## Nice to have

- [ ] Create and endpoint to update resource order
- [ ] Create username blocklist (To allow listas.io/username urls)
- [ ] Create follow endpoint (Public Lists)
- [ ] Avatar
- [ ] Google login
- [ ] Check if resource is duplicated
- [x] IDs property should be `id` instead of `_id`
- [x] Check if resource URL does not resolve

## Nice to have less priority 

- [ ] Profile section
- [ ] Settings
- [ ] Create endpoint to check if user slug exists
- [ ] Remove utm tag from URLs

## Discussion

- [ ] Why are list IDs `Option<ID>`? When would it be `None`?
- [ ] Would it be too much work to intragrate OpenAPI/Swagger? https://paperclip.waffles.space/actix-plugin.html
